apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-apps
  namespace: argocd
spec:
  project: default # ← AppProject 안 쓰는 핵심
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: alloy
      targetRevision: 2.0.2
      helm:
        valueFiles:
          - $values/values/argocd-apps.yaml

    - repoURL: https://github.com/dr-kube/dr-kube.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
