apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crash-test
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/dr-kube/dr-kube.git
      targetRevision: main
      path: charts/dr-kube-test
      helm:
        valueFiles:
          - $values/values/crash-test.yaml

    - repoURL: https://github.com/dr-kube/dr-kube.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
