# Chaos Mesh 실험: Online Boutique Frontend OOM 유발
# 목적: Frontend 파드 메모리 스트레스 → OOMKilled 유발 → 에이전트 감지
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: boutique-frontend-oom
  namespace: chaos-mesh
spec:
  mode: one
  duration: 3m
  selector:
    namespaces:
      - online-boutique
    labelSelectors:
      app: frontend
  stressors:
    memory:
      workers: 4
      size: 256M  # 256MB x 4 workers = 1GB 이상 메모리 할당 (limit: 128Mi)
