# Chaos Mesh 실험: 단일 Pod 반복 종료 -> 서비스 다운타임
# 방법: Schedule + PodChaos로 30초 간격 반복 pod-kill
apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: boutique-replica-shortage
  namespace: chaos-mesh
spec:
  schedule: "@every 30s"
  type: PodChaos
  historyLimit: 2
  concurrencyPolicy: Allow
  podChaos:
    action: pod-kill
    mode: one
    selector:
      namespaces:
        - online-boutique
      labelSelectors:
        app: checkoutservice
