# Chaos Mesh 실험: Online Boutique CheckoutService Pod 강제 종료
# 목적: CheckoutService 파드 강제 종료 → Pod Restart → 서비스 복구 과정 관찰
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: boutique-checkoutservice-kill
  namespace: chaos-mesh
spec:
  action: pod-kill
  mode: one
  duration: 1m
  selector:
    namespaces:
      - online-boutique
    labelSelectors:
      app: checkoutservice
