# Chaos Mesh 실험: 서비스 디스커버리 실패
# 방법: productcatalogservice pod kill -> frontend/recommendation에서 gRPC 연결 에러 발생
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: boutique-dns-failure
  namespace: chaos-mesh
spec:
  action: pod-kill
  mode: all
  duration: 3m
  selector:
    namespaces:
      - online-boutique
    labelSelectors:
      app: productcatalogservice
