{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dr-kube-agent.fullname" . }}
  labels:
    {{- include "dr-kube-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  copilot-token: {{ .Values.secrets.copilotToken | quote }}
  slack-bot-token: {{ .Values.secrets.slackBotToken | quote }}
  slack-channel: {{ .Values.secrets.slackChannel | quote }}
  github-token: {{ .Values.secrets.githubToken | quote }}
{{- end }}
