apiVersion: v1
kind: Service
metadata:
  name: {{ include "dr-kube-agent.fullname" . }}
  labels:
    {{- include "dr-kube-agent.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.webhook.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dr-kube-agent.selectorLabels" . | nindent 4 }}
